plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gabedeveloper.xodo'
    compileSdk 34
    ndkVersion '26.1.10909125'

    defaultConfig {
        applicationId "com.gabedeveloper.xodo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1"

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

